### ISSUE TITLE
Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by ongkay** [lucky-chap/kaminari#1]
hi, I just tried cloning this template, `npm install`, and `npm run dev`, but the result is like this.

how come ? I didn't change any code at all.

![image](https://user-images.githubusercontent.com/101445234/209892193-0a324b2b-5c60-4697-bf18-441c20a62463.png)

**Comment by lucky-chap** [comment]
So sorry for that experience. I’d fix it up right away. So sorry about this 🙏

**Comment by lucky-chap** [comment]
Please is the error still persisting? I have fixed it. Please pull new changes

**Comment by lucky-chap** [comment]
Fixed
