### ISSUE TITLE
next.config.js typescript rule

### ISSUE THREAD

**Issue by lucky-chap** [lucky-chap/kaminari#5]
Remove `ignoreBuildErrors: true` statement in `next.config.js`

**Comment by lucky-chap** [comment]
In production mode, the app does not deploy to Vercel because of some unknown bug. You can reach out to fix it if you want. Just open a new PR!

**Comment by 0papi** [comment]
Assign this to me

**Comment by lucky-chap** [comment]
> Assign this to me

It's yours!

**Comment by lucky-chap** [comment]
Fixed
